### ISSUE TITLE
Question about config file

### ISSUE THREAD

**Issue by choma** [poralix/directadmin-bfm-csf#1]
Hi,
First I want to say thank you!!, this is pure gold, and saved my day with an old server which is now more safe :)

Anyway, I'm new to CSF and I'm not sure if I understand correctly how the `/root/directadmin-bfm-csf.conf` file works here.

I first installed without this file, and then I realized that I needed `8080` port open. So I created the file with:
```
WEB_PORTS="80 443 8080";
```
And installed it again (maybe I shouldn't have done this).

But the port was still blocked, so I added the port to `TCP_IN` in the file `/etc/csf/csf.conf`, and ran `csf -r`, then it worked.
Can you explain a bit how does this works?

**Comment by gralex54** [comment]
Hello,

Thank you for your interest. The config line:

```
WEB_PORTS="80 443 8080";
```

tells the script to block access to ports 80, 443, 8080 for an IP, from which attacks to wordpress (for example) are coming.

Regards,
Alex.
